frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Order;
use common\models\OrderItem;
use common\models\Product;
use common\models\Category;
use common\models\Coupon;
use frontend\models\forms\RebateForm;
use frontend\components\FrontendController;
use yz\shoppingcart\ShoppingCart;

class CartController extends FrontendController
{
    public $rebate = null;
    public $promo  = null;
    public $enableCsrfValidation = false;

    public function actionAdd()
    {
        if (Yii::$app->request->isAjax && $data = Yii::$app->request->post()) {
            $id = explode(":", $data['id']);
            $id = $id[0];
            
            $product = Product::findOne($id);
            if ($product) {
                $cart = Yii::$app->cart;
                $cart->put($product);
                \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                return [
                    'code' => 100,
                    'str'  => self::cartString(),
                    'num'  => $cart->getCount(),
                ];
            }
        }
    }

    public function actionUpdate()
    {
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();
            $id = explode(":", $data['id']);
            $id = $id[0];
            
            $quantity = explode(":", $data['quantity']);
            $quantity = (int) $quantity[0];

            $product = Product::findOne($id);
            if ($product) {
                Yii::$app->cart->update($product, $quantity);
                
                $this->redirect('/vasha-korzina/');
            }
       }
    }

    public function actionPromo()
    {
        if (Yii::$app->request->isAjax) {
            $data = Yii::$app->request->post();
            $promo = explode(":", $data['promo']);
            $promo = $promo[0];
            
            $this->redirect("/vasha-korzina/$promo/");
        }               
    }

    public function actionOrder($promo = null)
    {
        if ($promo !== null) {
            $this->promo  = $promo;
            $this->rebate = Coupon::getRebateByPromo($this->promo);
        }

        $order = new Order();

        $cart  = Yii::$app->cart;            /* @var $cart ShoppingCart */
        $products = $cart->getPositions();   /* @var $products Product[] */      
        
        if ($this->rebate) {
            $cart->on(ShoppingCart::EVENT_COST_CALCULATION, function ($event) {
                $event->discountValue = $this->rebate;
            });
        }

        if ($order->load(Yii::$app->request->post()) && $order->validate()) {
            
            $transaction = $order->getDb()->beginTransaction();
            
                $order->rebate      = $this->rebate;
                $order->total       = $cart->getCost();
                $order->total_with  = $cart->getCost(true);
                $order->save(false);
                $id = Yii::$app->db->getLastInsertID();

                foreach($products as $product) :
                    
                    $orderItem = new OrderItem();
                        $orderItem->order_id   = $order->id;
                        $orderItem->title      = $product->title;
                        $orderItem->price      = $product->getPrice();
                        $orderItem->product_id = $product->id;
                        $orderItem->quantity   = $product->getQuantity();

                    if (!$orderItem->save(false)) {
                        
                        $transaction->rollBack();
                        
                        Yii::$app->session->addFlash('error', 'Невозможно разместить заказ. Пожалйста, свяжитесь с нами!');
                        return $this->redirect('/');
                    }
                    
                endforeach;

            $transaction->commit();
            
            if ($promo !== null) {
                Coupon::makeClose($this->promo);
            }
            
            Yii::$app->cart->removeAll();

            Yii::$app->session->addFlash('success', 'Спасибо за Ваш заказ. Мы свяжемся с Вами в блтжайшее время!');
            
            $order->sendEmail();

            $model = Order::find()->where(['id' => $id])->one();
            $model->number = \common\components\OrderNumber::makeNumber($id);
            $model->save(false);

            return $this->redirect("/privetstvie/$model->number/");
        }

        return $this->render('order', [
            'order'    => $order,
            'products' => $products,
            'rebate'   => $this->rebate,
        ]);
    }

    public function actionRemove($id)
    {
        $product = Product::findOne($id);
        if ($product) {
            Yii::$app->cart->remove($product);
            $this->redirect('/vasha-korzina/');
        }
    }

    public function actionAdvert($zakaz)
    {
        return $this->render('advert', [
            'zakaz' => $zakaz,
        ]);
    }

    public static function cartString()
    {
        $cart = \Yii::$app->cart;
        $num = 0;
        if ($cart->getIsEmpty()) :
            $res = 'В корзине нет товаров';
        else :
            $num = $cart->getCount();
            $sum = $cart->getCost();
            $hvost = $num % 10;
            switch ($hvost) :
                case 1:
                    $hvost = '';
                    break;
                case 2:
                case 3:
                case 4:
                    $hvost = 'а';
                    break;
                default :
                    $hvost = 'ов';
                    break;
            endswitch;

            if (in_array($num, [11, 12, 13, 14, 15, 16, 17, 18, 19])) {
                $hvost = 'ов';
            }

            $res = $num . ' товар' . $hvost . ' на ' . $sum . ' р.';
        endif;

        return $res;
    }
}

frontend/views/cart/_basket-form.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<div class="basket-form">
    <h4><?=HTML::encode('Оформление заказа')?></h4>
    <p><?=HTML::encode('Внимание! Все поля обязательны для заполнения.')?></p>

    <?php $form = ActiveForm::begin([]); ?>
        <div class="basket-inputs-holder">
            <div class="basket-form-inputs-left">

                <?php echo Html::activeInput('string', $order, 'fio',   ['placeholder' => HTML::encode('ФИО'),]); ?>
                <?php echo Html::activeInput('string', $order, 'phone', ['placeholder' => HTML::encode('Номер телефона'),]); ?>
                <?php echo Html::activeInput('string', $order, 'email', ['placeholder' => HTML::encode('Адрес электронной почты'),]); ?>
           
            </div>
            <div class="basket-form-inputs-right">
                <?php echo HTML::activeTextArea($order, 'address', ['placeholder' => HTML::encode('Адрес доставки'),]); ?>
            </div>
        </div>
        <div class="add-to-basket">
            <?= Html::submitButton(HTML::encode('Оформить заказ'), ['class' => 'dbr-btn']) ?>
        </div>
    <?php ActiveForm::end(); ?>
</div>

frontend/views/cart/advert.php
<?php

use yii\helpers\Html;
use common\models\Order;

$this->title = Html::encode('Заказ оформлен! Номер заказа ' . $zakaz); //
//$this->params['breadcrumbs'][] = ['label' => HTML::encode(Category::getSeriaById($model->category_id)), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->params['logoLink'] = true;
?>

<h1><?= HTML::encode($this->title) ?></h1>

<div class="thanx-page">
    <div class="thanx-block">
        <p>Спасибо за заказ!</p>
    </div>
</div>
<br>

frontend/views/cart/list.php
<?php
use \yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $products common\models\Product[] */
?>
<h1>Your cart</h1>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4">

        </div>
        <div class="col-xs-2">
            Price
        </div>
        <div class="col-xs-2">
            Quantity
        </div>
        <div class="col-xs-2">
            Cost
        </div>
        <div class="col-xs-2">

        </div>
    </div>
    <?php foreach ($products as $product):?>
    <div class="row">
        <div class="col-xs-4">
            <?= Html::encode($product->title) ?>
        </div>
        <div class="col-xs-2">
            $<?= $product->price ?>
        </div>
        <div class="col-xs-2">
            <?= $quantity = $product->getQuantity()?>

            <?= Html::a('-', ['cart/update', 'id' => $product->getId(), 'quantity' => $quantity - 1], ['class' => 'btn btn-danger', 'disabled' => ($quantity - 1) < 1])?>
            <?= Html::a('+', ['cart/update', 'id' => $product->getId(), 'quantity' => $quantity + 1], ['class' => 'btn btn-success'])?>
        </div>
        <div class="col-xs-2">
            $<?= $product->getCost() ?>
        </div>
        <div class="col-xs-2">
            <?= Html::a('×', ['cart/remove', 'id' => $product->getId()], ['class' => 'btn btn-danger'])?>
        </div>
    </div>
    <?php endforeach ?>
    <div class="row">
        <div class="col-xs-8">

        </div>
        <div class="col-xs-2">
            Total: $<?= $total ?>
        </div>
        <div class="col-xs-2">
            <?= Html::a('Order', ['cart/order'], ['class' => 'btn btn-success'])?>
        </div>
    </div>
</div>

frontend/views/cart/order.php
<?php

use Yii;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use common\models\Product;

/* @var $this yii\web\View */
/* @var $products common\models\Product[] */

$this->title = Html::encode('Ваша корзина');

$this->params['breadcrumbs'][] = $this->title;

$this->params['logoLink'] = true;
?>

<h1><?= HTML::encode($this->title) ?></h1>
<?php $cartNumber  = \Yii::$app->cart->getCount(); ?>
<?php if ($cartNumber > 0) : ?>
<div class="basket-holder">
    <div class="basket-left">
        <div class="goods">
            <?php foreach ($products as $product): ?>
                <div class="good-item">
                    <div class="good-holder">
                        <div class="good-photo">
                            <?php
                            if (isset($product->photo)) {
                                echo Html::img(Yii::getAlias('@productUpload/' . $product->photo), ['width' => '100%']);
                            }
                            ?>
                        </div>
                        <div class="good-info-holder">
                            <?php $category = common\models\Category::getSlugById($product->category_id); ?>
                            <div class="good-title"><a href="<?= "/$category/$product->slug.html" ?>"><?= HTML::encode($product->title) ?></a></div>
                            <div class="good-info"><?= Html::encode($product->short)?></div>
                        </div>
                        <?php // echo 'quantity= '.$product->quantity ?>
                        <div class="quantity">
                            <select title="<?=$product->getId()?>">
                                <?php for ($i = 1; $i <= 10; $i++) : ?>
                                    <option 
                                        value="<?= $i ?>"                                       
                                        <?php if ($product->quantity == $i) echo ' selected="selected"'; ?>
                                    >
                                        <?= $i ?>
                                    </option>
                                <?php endfor ?>
                            </select>
                        </div>
                        <div class="good-price"><?= Html::encode(Yii::$app->formatter->asInteger($product->price) . ' руб.') ?></div>
                    </div>
                    <div class="delete-item">
                        <a href="<?='/cart/remove/' . $product->getId() . '/'?>">
                            <?=HTML::encode('Удалить')?>
                        </a>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
        <div class="basket-summ-block">
            <div class="basket-summ">
                <?php $cart = Yii::$app->cart ?>
                <?php $tot = $cart->getCost() ?>
                <?=  Html::encode('Сумма: ' . Yii::$app->formatter->asInteger($tot) . ' руб.') ?>
            </div>
            <div class="basket-sale">
                <?=  Html::encode('Скидка ' . $rebate . '%: ' . Yii::$app->formatter->asInteger($tot * $rebate) . ' руб.') ?>
            </div>
            <div class="basket-itogo">
                <?= Html::encode('Итого: ' .     Yii::$app->formatter->asInteger($cart->getCost(true)) . ' руб.') ?>
            </div>
        </div>
    </div>

    <div class="basket-right">

        <div class="basket-info">
            <?= Html::encode('Возникли вопросы или сложности с оформлением заказа? Мы готовы помочь! Позвоните в наш колл-центр по номеру 8 800 2000 000.')?>
        </div>

        <div class="promo">
            <div class="promo-header">
                <span><?= Html::encode('У вас есть промо-код?')?></span>
            </div>

            <input  id="promo-value"  type="text">
            <button id="promo-button" class="dbr-btn"><?= Html::encode('АКТИВИРОВАТЬ')?></button>
        </div>

    </div>
</div>

<div class="basket-form">
    <h4><?=HTML::encode('Оформление заказа')?></h4>
    <p><?=HTML::encode('Внимание! Все поля обязательны для заполнения.')?></p>

    <?php $form = ActiveForm::begin([]); ?>
        <div class="basket-inputs-holder">
            <div class="basket-form-inputs-left">

                <?php echo Html::activeInput('string', $order, 'fio',   ['placeholder' => HTML::encode('ФИО'),]); ?>
                <?php echo Html::activeInput('string', $order, 'phone', ['placeholder' => HTML::encode('Номер телефона'),]); ?>
                <?php echo Html::activeInput('string', $order, 'email', ['placeholder' => HTML::encode('Адрес электронной почты'),]); ?>
           
            </div>
            <div class="basket-form-inputs-right">
                <?php echo HTML::activeTextArea($order, 'address', ['placeholder' => HTML::encode('Адрес доставки'),]); ?>
            </div>
        </div>
        <div class="add-to-basket">
            <?= Html::submitButton(HTML::encode('Оформить заказ'), ['class' => 'dbr-btn']) ?>
        </div>
    <?php ActiveForm::end(); ?>
</div>

<?php endif; ?>

frontend/views/cart/rebate.php
<?php

use yii\helpers\Html;

$this->params['logoLink'] = true;



?>
<br><br>
<?= $promo ? $promo : 'Very Bed!';?>
<br><br>

frontend/views/cart/update.php
<?php
/* @var $this yii\web\View */
$this->params['logoLink'] = true;
?>
<h1>cart/update</h1>

<?php

echo 'id= ' . $id . "<br>" . 'quant= ' . $quant;

?>